# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.UUIDField(db_column=b'employeeId', primary_key=True, serialize=False)),
                ('employeeJobnumber', models.CharField(db_column=b'employeeJobnumber', max_length=100)),
                ('eemployeeTitle', models.CharField(db_column=b'eemployeeTitle', max_length=100)),
                ('employeeSex', models.IntegerField(db_column=b'employeeSex', max_length=1)),
                ('employeeFirstname', models.CharField(db_column=b'employeeFirstname', max_length=100, null=True)),
                ('employeeLastname', models.CharField(db_column=b'employeeLastname', max_length=100, null=True)),
                ('employeeContact', models.CharField(db_column=b'employeeContact', max_length=100, null=True)),
                ('employeeSalary', models.DecimalField(db_column=b'employeeSalary', decimal_places=2, max_digits=8, max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeId', models.UUIDField(db_column=b'recipeId', primary_key=True, serialize=False)),
                ('recipeName', models.CharField(db_column=b'recipeName', max_length=100)),
                ('recipePrice', models.DecimalField(db_column=b'recipePrice', decimal_places=2, max_digits=8, max_length=10)),
                ('recipeDescription', models.TextField(db_column=b'recipeDescription', null=True)),
                ('recipeImagepath', models.CharField(db_column=b'recipeImagepath', max_length=200)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantId', models.UUIDField(db_column=b'restaurantId', primary_key=True, serialize=False)),
                ('restaurantName', models.CharField(db_column=b'restaurantName', max_length=200)),
                ('restaurantLocation', models.CharField(db_column=b'restaurantLocation', max_length=200, null=True)),
                ('restaurantContact', models.CharField(db_column=b'restaurantContact', max_length=50, null=True)),
                ('restaurantOpenTime', models.TimeField(db_column=b'restaurantOpenTime')),
                ('restaurantCloseTime', models.TimeField(db_column=b'restaurantCloseTime')),
                ('restaurantMenu', jsonfield.fields.JSONField(db_column=b'restaurantMenu', max_length=200, null=True)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeBelong',
            field=models.ForeignKey(db_column=b'employeeBelong', on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant'),
        ),
    ]
