# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.IntegerField(db_column=b'employeeId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeId',
            field=models.IntegerField(db_column=b'recipeId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantId',
            field=models.IntegerField(db_column=b'restaurantId', primary_key=True, serialize=False),
        ),
    ]
