# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170916_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeBelong',
            field=models.ForeignKey(db_column=b'employeeBelong', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='core.Restaurant'),
        ),
    ]
