# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170916_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantImage',
            field=models.CharField(db_column=b'restaurantImage', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantSales',
            field=jsonfield.fields.JSONField(db_column=b'restaurantSales', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeSex',
            field=models.IntegerField(db_column=b'employeeSex'),
        ),
    ]
