# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170917_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurantMenu',
        ),
    ]
