# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_restaurant_restaurantmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantLongtitude',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantMagnitude',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
