# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170918_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurantMagnitude',
            new_name='restaurantLatitude',
        ),
    ]
