# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170918_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeePhoto',
            field=models.CharField(db_column=b'employeePhoto', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeTitle',
            field=models.CharField(db_column=b'employeeTitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantLatitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantLongtitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
